# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CmdLine@2
  inputs:
    script: 'git clone https://github.com/seafoodguy/spring-petclinic-asr-helmchart.git'
    workingDirectory: '$(System.ArtifactsDirectory)'



- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'iconinfo o365'
    azureResourceGroup: 'AL-AKS'
    kubernetesCluster: 'alfredk8s'
    namespace: 'testns'
    command: 'install'
    chartType: 'FilePath'
    chartPath: '$(System.ArtifactsDirectory)'
    chartVersion: '29'
    
