# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadGitHubRelease@0
  inputs:
    connection: 'seafoodguytoken'
    userRepository: 'seafoodguy/spring-petclinic-asr-helmchart'
    defaultVersionType: 'main'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'iconinfo o365'
    azureResourceGroup: 'AL-AKS'
    kubernetesCluster: 'alfredk8s'
    namespace: 'testns'
    command: 'install'
    chartType: 'FilePath'
    chartPath: '$(System.ArtifactsDirectory)'
    chartVersion: '29'
    
