# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
    - task: HelmInstaller@0
      inputs:
        helmVersion: '3.6.0'
        checkLatestHelmVersion: false
        installKubectl: true
    - task: CmdLine@2
      inputs:
        script: |
          git config --global user.name azuredevops
          git config --global user.email alfredshek@icon-info.com.hk
          git clone https://github.com/seafoodguy/spring-petclinic-asr-helmchart.git
          cd spring-petclinic-asr-helmchart
          sed -i -r 's,repository: (.+),repository: iconalfred.azurecr.io/seafoodguyspringpetclinicasr,' values.yaml
          sed 's/tag:.*/tag: 30/g' values.yaml
          cat values.yaml
          export HELM_EXPERIMENTAL_OCI=1
          helm package .
    - task: HelmDeploy@0
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'iconinfo o365'
        azureResourceGroup: 'AL-AKS'
        kubernetesCluster: 'alfredk8s'
        useClusterAdmin: true
        namespace: 'testns'
        command: 'install'
        chartType: 'FilePath'
        chartPath: '/home/vsts/work/1/s/spring-petclinic-asr-helmchart/spring-petclinic-1.0.0.tgz'
        releaseName: 'spring-petclinic'
        arguments: '--tag 30'
        